name: path_provider_foundation
version: 2.6.0
description: Stub - no objective_c dependency
environment:
  sdk: '>=3.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface: ^2.1.3
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PathProviderPlugin
      macos:
        pluginClass: PathProviderPlugin
